# -*- coding: utf-8 -*-
"""MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ug8pho0YNbtJDf0GbmDimamSR28st5di
"""

import torch
import numpy as np
import matplotlib.pyplot as plt
from torchvision import datasets

device = torch.device('cuda')
print(f"GPU: {torch.cuda.get_device_name(0)}")
print(f"Bellek: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

print(f'PyTorch: {torch.__version__}')
print(f'GPU: {torch.cuda.is_available()}')

from torchvision import datasets

train_data = datasets.MNIST(root='./data', train=True, download=True)
test_data  = datasets.MNIST(root='./data', train=False, download=True)

print(f'Eğitim: {len(train_data)} görüntü')
print(f'Test:   {len(test_data)} görüntü')

img, label = train_data[0]
plt.imshow(img, cmap='gray')
plt.title(f'Etiket: {label}')
plt.axis('off')
plt.show()

import numpy as np

# train_data'daki tüm etiketleri liste olarak topla
# train_data[i][1] -> i. görüntünün etiketi (rakamı)
labels = [train_data[i][1] for i in range(len(train_data))]

# Her rakamdan kaç tane var say
# unique → [0,1,2,3,4,5,6,7,8,9]
# counts → [5923, 6742, ...]

"""
`train_data[0]` -> `(görüntü, 5)` döndürür
`train_data[0][1]` -> sadece etiketi alır → `5`

Yani 60000 görüntünün hepsinin etiketini alıp listeye koyuyor:
```
[5, 0, 4, 1, 9, 2, 1, 3, ...]
"""

unique, counts = np.unique(labels, return_counts=True)
#Etiketler dizisi içindeki benzersiz öğeleri belirleme ve her benzersiz öğenin kaç kez geçtiğini sayma

# Grafik boyutu
plt.figure(figsize=(10, 4))
# Bar grafik
plt.bar(unique, counts, color='steelblue')
# Başlık ve eksen isimleri
plt.title('Sınıf Dağılımı')
plt.xlabel('Rakam')
plt.ylabel('Sayı')
# X ekseninde 0-9 göster
plt.xticks(range(10))
plt.show()

# 2 satır 5 sütun = 10 kutucuk oluştur (0-9 için)
fig, axes = plt.subplots(2, 5, figsize=(12, 5))
# 2D diziyi 1D yap -> axes[0], axes[1]... diye erişelim
axes = axes.flatten()

# 0'dan 9'a kadar her rakam için döngü
for i in range(10):
    # labels listesinde i rakamının ilk geçtiği yeri bul
    idx = labels.index(i)
    # o indexteki görüntü ve etiketi al
    img, label = train_data[idx]
    # ilgili kutucuğa görüntüyü çiz (gri renk)
    axes[i].imshow(img, cmap='gray')
    # kutucuğa başlık ekle
    axes[i].set_title(f'Rakam: {label}')
    # eksenleri gizle
    axes[i].axis('off')

# genel başlık
plt.suptitle('Her Rakamdan Örnek', fontsize=14)
plt.tight_layout()
plt.show()

img, label = train_data[0]
print(type(img))
# model bunu anlamaz, sayı ister

import torchvision.transforms as transforms

transform = transforms.Compose([ #birden fazla transformu sırayla uygulamak için "compose"
    transforms.ToTensor(),  # PIL Image -> sayı dizisine çevir
])

img_tensor = transform(img)
print(img_tensor.shape)
print(img_tensor.min(), img_tensor.max())#->pixel değerleri 0-255'ten 0-1 e düşürüldü

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))# piksel değerlerini dengeledi

    #0.1307 -> MNIST'in ortalama piksel değeri
    #0.3081 -> MNIST'in standart sapması

])

train_data = datasets.MNIST(root='./data', train=True,  download=True, transform=transform)
test_data  = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

print('Transform uygulandı')

#60.000 görüntüyü modele tek seferde veremeyiz, bellek patlar. DataLoader bunları küçük gruplar (batch) halinde veriyor.

from torch.utils.data import DataLoader

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)#shuffle=True neden? Eğitimde karıştırıyoruz — model hep aynı sırada görürse ezberlemeye başlar.
test_loader  = DataLoader(test_data,  batch_size=32, shuffle=False) #shuffle=False neden test'te? Test'te karıştırmaya gerek yok, sadece ölçüyoruz.

print(f'Eğitim batch sayısı: {len(train_loader)}')
print(f'Test batch sayısı:   {len(test_loader)}')

# PyTorch'un sinir ağı modülünü içe aktar
import torch.nn as nn

# nn.Module'den miras alan model sınıfı
class MNISTModel(nn.Module):

    def __init__(self):
        super().__init__()  # nn.Module'ü başlat

        # 1 kanallı görüntüyü al, 32 farklı özellik çıkar
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3)

        # 32 özelliği al, 64 farklı özellik çıkar
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3)

        # Görüntüyü yarıya küçült (28x28 → 14x14)
        self.pool  = nn.MaxPool2d(2)

        # Düzleştirilmiş veriyi 128 nörona bağla
        self.fc1 = nn.Linear(64 * 12 * 12, 128)

        # 128 nöronu 10 çıktıya bağla (0-9 rakamları)
        self.fc2   = nn.Linear(128, 10)

        # Negatif değerleri sıfırla
        self.relu  = nn.ReLU()

    # Görüntü modelden geçerken bu fonksiyon çalışır
    def forward(self, x):
        x = self.relu(self.conv1(x))      # conv1 → relu
        x = self.pool(self.relu(self.conv2(x)))  # conv2 → relu → pool
        x = x.view(x.size(0), -1)         # 3D → 1D düzleştir
        x = self.relu(self.fc1(x))         # fc1 → relu
        x = self.fc2(x)                    # fc2 → 10 çıktı
        return x

# Modeli GPU'ya taşı
model = MNISTModel().to('cuda')
print(model)

import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001) #lr= learning rate

print('✅ Loss ve Optimizer hazır')

"""# **Loss (CrossEntropyLoss)**
**Modelin ne kadar yanıldığını ölçüyor.**

Gerçek: 5

Model tahmini: 3

Loss: yüksek → çok yanlış!

Gerçek: 5

Model tahmini: 5

Loss: düşük -> doğru!

# **Optimizer (Adam)**

**Loss'a bakarak modelin ağırlıklarını düzeltiyor.**

Loss yüksek -> "bir şeyler yanlış, düzelt!"

Loss düşük  -> "iyi gidiyoruz, devam!"

Şöyle düşün: Loss sınav notu, Optimizer ise notuna göre nasıl çalışacağını söyleyen hoca.
"""

DEVICE = 'cuda'
NUM_EPOCHS = 5

for epoch in range(1, NUM_EPOCHS + 1):
    model.train()
    total_loss, correct, total = 0, 0, 0

    for images, labels in train_loader:
        images, labels = images.to(DEVICE), labels.to(DEVICE)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    acc = correct / total
    print(f'Epoch [{epoch}/{NUM_EPOCHS}] Loss: {total_loss/len(train_loader):.4f} | Acc: {acc:.4f}')

model.eval()
correct, total = 0, 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        outputs = model(images)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

print(f'Test Accuracy: {correct/total:.4f}')

from sklearn.metrics import confusion_matrix
import seaborn as sns

all_preds, all_labels = [], []

model.eval()
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(DEVICE)
        outputs = model(images)
        preds = outputs.argmax(dim=1).cpu().numpy()
        all_preds.extend(preds)
        all_labels.extend(labels.numpy())

cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=range(10), yticklabels=range(10))
plt.title('Confusion Matrix')
plt.xlabel('Tahmin')
plt.ylabel('Gerçek')
plt.show()